export enum SchoolTypeEnum {
  PRIMARY = 'PRIMARY',
  UPPER_PRIMARY = 'UPPER_PRIMARY',
  SECONDARY = 'SECONDARY',
  HIGHER_SECONDARY = 'HIGHER_SECONDARY',
  BACHELOR = 'BACHELOR',
  MASTER = 'MASTER',
  DOCTORATE = 'DOCTORATE',
  OTHERS = 'OTHERS',
}
